server:
  port: 9527

spring:
  application:
    name: springclud-zuul-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: zuul-9527.com
    prefer-ip-address: true


info:
  app.name: springlcoud-zuul
  company.name: www.springloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /linjd
  ignored-services: "*"
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**